# Generated by Django 4.2.6 on 2024-04-04 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Collection',
            new_name='collection',
        ),
    ]
