# Generated by Django 4.2.6 on 2024-04-05 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_rename_collection_product_collection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='title',
            field=models.CharField(default=True, max_length=255),
        ),
    ]
